[[changes-in-2-4-since-2-3]]
= Changes in 2.4 Since 2.3
:page-section-summary-toc: 1

This section describes the changes between version 2.3 and version 2.4.
See xref:appendix/change-history.adoc[Change History] for changes in previous versions.

[[rabbitlistener-changes]]
== `@RabbitListener` Changes

`MessageProperties` is now available for argument matching.
See xref:amqp/receiving-messages/async-annotation-driven/enable-signature.adoc[Annotated Endpoint Method Signature] for more information.

[[rabbitadmin-changes]]
== `RabbitAdmin` Changes

A new property `recoverManualDeclarations` allows recovery of manually declared queues/exchanges/bindings.
See xref:amqp/broker-configuration.adoc#declarable-recovery[Recovering Auto-Delete Declarations] for more information.

[[remoting-support]]
== Remoting Support

Support remoting using Spring Framework’s RMI support is deprecated and will be removed in 3.0. See Spring Remoting with AMQP for more information.

[[stream-support-changes]]
== Stream Support Changes

`RabbitStreamOperations` and `RabbitStreamTemplate` have been deprecated in favor of `RabbitStreamOperations2` and `RabbitStreamTemplate2` respectively; they return `CompletableFuture` instead of `ListenableFuture`.
See xref:stream.adoc[Using the RabbitMQ Stream Plugin] for more information.

[[message-converter-changes]]
== Message Converter Changes

The `Jackson2JsonMessageConverter` can now determine the charset from the `contentEncoding` header.
See xref:amqp/message-converters.adoc#json-message-converter[`Jackson2JsonMessageConverter`] for more information.

