[[spring-amqp-reference]]
= Spring AMQP
ifdef::backend-html5[]
:revnumber: ''
endif::[]
:toc: left
:toclevels: 4
:numbered:
:icons: font
:hide-uri-scheme:
Mark Pollack; Mark Fisher; Oleg Zhurakousky; Dave Syer; Gary Russell; Gunnar Hillert; Artem Bilan; Stéphane Nicoll; Arnaud Cogoluègnes; Jay Bryant

ifdef::backend-html5[]
*{project-version}*

NOTE: This documentation is also available as https://docs.spring.io/spring-amqp/docs/current/reference/pdf/spring-integration-amqp.pdf[PDF].
endif::[]

ifdef::backend-pdf[]
NOTE: This documentation is also available as https://docs.spring.io/spring-amqp/docs/current/reference/html/index.html[HTML].
endif::[]

(C) 2010 - 2021 by VMware, Inc.

Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.


== Preface

include::preface.adoc[]

include::whats-new.adoc[]

== Introduction

This first part of the reference documentation is a high-level overview of Spring AMQP and the underlying concepts.
It includes some code snippets to get you up and running as quickly as possible.

include::quick-tour.adoc[]

== Reference

This part of the reference documentation details the various components that comprise Spring AMQP.
The <<amqp,main chapter>> covers the core classes to develop an AMQP application.
This part also includes a chapter about the <<sample-apps,sample applications>>.

include::amqp.adoc[]

include::logging.adoc[]

include::sample-apps.adoc[]

include::testing.adoc[]

== Spring Integration - Reference

This part of the reference documentation provides a quick introduction to the AMQP support within the Spring Integration project.

include::si-amqp.adoc[]

[[resources]]
== Other Resources

In addition to this reference documentation, there exist a number of other resources that may help you learn about AMQP.

include::further-reading.adoc[]

[appendix]
include::appendix.adoc[]
