[[spring-amqp-reference]]

= Spring AMQP

:toc:

== Preface

include::preface.adoc[]

== Introduction

This first part of the reference documentation is a high-level overview of Spring AMQP and the underlying concepts and some code snippets that will get you up and running as quickly as possible.

include::quick-tour.adoc[]

include::whats-new.adoc[]

== Reference

This part of the reference documentation details the various components that comprise Spring AMQP.
The <<amqp,main chapter>> covers the core classes to develop an AMQP application.
This part also includes a chapter about the <<sample-apps,sample applications>>.

include::amqp.adoc[]

include::logging.adoc[]

include::sample-apps.adoc[]

include::testing.adoc[]

== Spring Integration - Reference

This part of the reference documentation provides a quick introduction to the AMQP support within the Spring Integration project.

include::si-amqp.adoc[]

[[resources]]

== Other Resources

In addition to this reference documentation, there exist a number of other resources that may help you learn about AMQP.

include::further-reading.adoc[]

[appendix]
include::appendix.adoc[]
