[[logging]]
=== Logging Subsystem AMQP Appenders

The framework provides logging appenders for several popular logging subsystems:

- logback (since Spring AMQP _version 1.4_)
- log4j2 (since Spring AMQP _version 1.6_)

The appenders are configured using the normal mechanisms for the logging subsystem, available properties are specified
in the following sections.

==== Common properties

The following properties are available with all appenders:

.Common Appender Properties
[cols="2l,2l,4", options="header"]
|===
| Property
| Default
| Description

| exchangeName
| logs
| Name of the exchange to publish log events to.

| exchangeType
| topic
| Type of the exchange to publish log events to - only needed if the appender declares the exchange.
See `declareExchange`.

| routingKeyPattern
| %c.%p
| Logging subsystem pattern format to use to generate a routing key.

| applicationId
|
| Application ID - added to the routing key if the pattern includes `%X{applicationId}`.

| senderPoolSize
| 2
| The number of threads to use to publish log events.

| maxSenderRetries
| 30
| How many times to retry sending a message if the broker is unavailable or there is some other error.
Retries are delayed like: `N ^ log(N)`, where `N` is the retry number.

| addresses
|
| A comma-delimited list of broker addresses: `host:port[,host:port]*` - overrides `host` and `port`.

| host
| localhost
| RabbitMQ host to connect to.

| port
| 5672
| RabbitMQ port to connect to.

| virtualHost
| /
| RabbitMQ virtual host to connect to.

| username
| guest
| RabbitMQ user to connect as.

| password
| guest
| RabbitMQ password for this user.

| useSsl
| false
| Use SSL for the RabbitMQ connection. See <<_rabbitconnectionfactorybean_and_configuring_ssl>>

| sslAlgorithm
| null
| The SSL algorithm to use.

| sslPropertiesLocation
| null
| Location of the SSL properties file.

| keyStore
| null
| Location of the keystore.

| keyStorePassphrase
| null
| Passphrase for the keystore.

| keyStoreType
| JKS
| The keystore type.

| trustStore
| null
| Location of the truststore.

| trustStorePassphrase
| null
| Passphrase for the truststore.

| trustStoreType
| JKS
| The truststore type.

| contentType
| text/plain
| `content-type` property of log messages.

| contentEncoding
|
| `content-encoding` property of log messages.

| declareExchange
| false
| Whether or not to declare the configured exchange when this appender starts.
Also see `durable` and `autoDelete`.

| durable
| true
| When `declareExchange` is `true` the durable flag is set to this value.

| autoDelete
| false
| When `declareExchange` is `true` the auto delete flag is set to this value.

| charset
| null
| Charset to use when converting String to byte[], default null (system default charset used).
If the charset is unsupported on the current platform, we fall back to using the system charset.

| deliveryMode
| PERSISTENT
| PERSISTENT or NON_PERSISTENT to determine whether or not RabbitMQ should persist the messages.

| generateId
| false
| Used to determine whether the `messageId` property is set to a unique value.

| clientConnection
Properties
| null
| A comma-delimited list of `key:value` pairs for custom client properties to the RabbitMQ connection.

|===

==== Log4j2 Appender

.Example log4j2.xml Snippet
[source, text]
----
<Appenders>
    ...
    <RabbitMQ name="rabbitmq"
        addresses="foo:5672,bar:5672" user="guest" password="guest" virtualHost="/"
        exchange="log4j2" exchangeType="topic" declareExchange="true" durable="true" autoDelete="false"
        applicationId="myAppId" routingKeyPattern="%X{applicationId}.%c.%p"
        contentType="text/plain" contentEncoding="UTF-8" generateId="true" deliveryMode="NON_PERSISTENT"
        charset="UTF-8"
        senderPoolSize="3" maxSenderRetries="5">
    </RabbitMQ>
</Appenders>
----

[IMPORTANT]
====
Starting with _versions 1.6.10, 1.7.3_, the log4j2 Appender publishes the messages to RabbitMQ on the calling thread by default.
This is because log4j2 does not create thread-safe events by default.
If the broker is down, the `maxSenderRetries` will be used to retry, with no delay between retries.
If you wish to restore the previous behavior of publishing the messages on separate threads (`senderPoolSize`), set the `async` property to `true`.
However, you will also need to configure log4j2 to use the `DefaultLogEventFactory` instead of the `ReusableLogEventFactory`.
One way to do that is to set the system property `-Dlog4j2.enable.threadlocals=false`.
If async publishing is used with the `ReusableLogEventFactory`, events will have a high likelihood of being corrupted due to cross-talk.
====

==== Logback Appender

.Example logback.xml Snippet
[source, text]
----
<appender name="AMQP" class="org.springframework.amqp.rabbit.logback.AmqpAppender">
    <layout>
        <pattern><![CDATA[ %d %p %t [%c] - <%m>%n ]]></pattern>
    </layout>
    <addresses>foo:5672,bar:5672</addresses>
    <abbreviation>36</abbreviation>
    <includeCallerData>false</includeCallerData>
    <applicationId>myApplication</applicationId>
    <routingKeyPattern>%property{applicationId}.%c.%p</routingKeyPattern>
    <generateId>true</generateId>
    <charset>UTF-8</charset>
    <durable>false</durable>
    <deliveryMode>NON_PERSISTENT</deliveryMode>
    <declareExchange>true</declareExchange>
</appender>
----

Starting with _version 1.7.1_, the Logback `AmqpAppender` provides  an `includeCallerData` option which is `false` by default.
Extracting caller data can be rather expensive because the log event has to create a throwable and inspect it to determine the calling location.
Therefore, by default, caller data associated with an event is not extracted when the event added to the event queue.
You can configure the appender to include caller data by setting the `includeCallerData` property to `true`.

Starting with _version 2.0.0_, the Logback `AmqpAppender` supports https://logback.qos.ch/manual/encoders.html[Logback encoders] with the `encoder` option. The `encoder` and `layout` options are mutually exclusive.

==== Customizing the Messages

By default AMQP appenders populates these message properties:
* deliveryMode
* contentType
* contentEncoding if configured
* messageId if `generateId` is configured
* timestamp of the log event
* appId if applicationId is configured

In addition they populate headers:
* categoryName of the log event
* level of the log event
* thread the name of the thread where log event happened
* location the stack trace of the log event call
* copy of all the MDC properties


Each of the appenders can be subclassed, allowing you to modify the messages before publishing.

.Customizing the Log Messages
[source, java]
----
public class MyEnhancedAppender extends AmqpAppender {

    @Override
    public Message postProcessMessageBeforeSend(Message message, Event event) {
        message.getMessageProperties().setHeader("foo", "bar");
        return message;
    }

}
----

==== Customizing the Client Properties

===== Simple String Properties

Each appender supports adding client properties to the RabbitMQ connection.

.logback
[source, xml]
----
<appender name="AMQP" ...>
    ...
    <clientConnectionProperties>foo:bar,baz:qux</clientConnectionProperties>
    ...
</appender>
----

.log4j2
[source, xml]
----
<Appenders>
    ...
    <RabbitMQ name="rabbitmq"
        ...
        clientConnectionProperties="foo:bar,baz:qux"
        ...
    </RabbitMQ>
</Appenders>
----

The properties are a comma-delimited list of `key:value` pairs; keys and values cannot contain commas or colons.

These properties appear on the RabbitMQ Admin UI when viewing the connection.

===== Advanced Technique for Logback

The Logback appender can be subclassed, allowing you to modify the client connection
properties before the connection is established:

.Customizing the Client Connection Properties
[source, java]
----
public class MyEnhancedAppender extends AmqpAppender {

    private String foo;

    @Override
    protected void updateConnectionClientProperties(Map<String, Object> clientProperties) {
        clientProperties.put("foo", this.foo);
    }

    public void setFoo(String foo) {
        this.foo = foo;
    }

}
----

Then add `<foo>bar</foo>` to logback.xml.

Of course, for simple String properties like this example, the previous technique can be used; subclasses allow
richer properties (such as adding a `Map` or numeric property).

With log4j2, subclasses are not supported, due to the way log4j2 uses static factory methods.

==== Providing a Custom Queue Implementation

The `AmqpAppenders` use a `BlockingQueue` to asynchronously publish logging events to RabbitMQ.
By default a `LinkedBlockingQueue` is used.
However, it is possible to supply any kind of custom `BlockingQueue` implementation.

.logback
[source, java]
----
public class MyEnhancedAppender extends AmqpAppender {

    @Override
    protected BlockingQueue<Event> createEventQueue() {
        return new ArrayBlockingQueue();
    }

}
----

The Log4j2 appender supports usage of a https://logging.apache.org/log4j/2.x/manual/appenders.html#BlockingQueueFactory[BlockingQueueFactory].

.log4j2
[source, xml]
----
<Appenders>
    ...
    <RabbitMQ name="rabbitmq"
              bufferSize="10" ... >
        <ArrayBlockingQueue/>
    </RabbitMQ>
</Appenders>
----
