[[logging]]
=== Logging Subsystem AMQP Appenders

The framework provides logging appenders for several popular logging subsystems:

- log4j (since Spring AMQP _version 1.1_)
- logback (since Spring AMQP _version 1.4_)
- log4j2 (since Spring AMQP _version 1.6_)

The appenders are configured using the normal mechanisms for the logging subsystem, available properties are specified
in the following sections.

==== Common properties

The following properties are available with all appenders:

.Common Appender Properties
[cols="2l,2l,4", options="header"]
|===
| Property
| Default
| Description

| exchangeName
| logs
| Name of the exchange to publish log events to.

| exchangeType
| topic
| Type of the exchange to publish log events to - only needed if the appender declares the exchange.
See `declareExchange`.

| routingKeyPattern
| %c.%p
| Logging subsystem pattern format to use to generate a routing key.

| applicationId
|
| Application ID - added to the routing key if the pattern includes `%X{applicationId}`.

| senderPoolSize
| 2
| The number of threads to use to publish log events.

| maxSenderRetries
| 30
| How many times to retry sending a message if the broker is unavailable or there is some other error.
Retries are delayed like: `N ^ log(N)`, where `N` is the retry number.

| addresses
|
| A comma-delimited list of broker addresses: `host:port[,host:port]*` - overrides `host` and `port`.

| host
| localhost
| RabbitMQ host to connect to.

| port
| 5672
| RabbitMQ port to connect to.

| virtualHost
| /
| RabbitMQ virtual host to connect to.

| username
| guest
| RabbitMQ user to connect as.

| password
| guest
| RabbitMQ password for this user.

| contentType
| text/plain
| `content-type` property of log messages.

| contentEncoding
|
| `content-encoding` property of log messages.

| declareExchange
| false
| Whether or not to declare the configured exchange when this appender starts.
Also see `durable` and `autoDelete`.

| durable
| true
| When `declareExchange` is `true` the durable flag is set to this value.

| autoDelete
| false
| When `declareExchange` is `true` the auto delete flag is set to this value.

| charset
| null
| Charset to use when converting String to byte[], default null (system default charset used).
If the charset is unsupported on the current platform, we fall back to using the system charset.

| deliveryMode
| PERSISTENT
| PERSISTENT or NON_PERSISTENT to determine whether or not RabbitMQ should persist the messages.

| generateId
| false
| Used to determine whether the `messageId` property is set to a unique value.

|===

==== Log4j Appender

.Example log4j.properties Snippet
[source, text]
----
log4j.appender.amqp.addresses=foo:5672,bar:5672
log4j.appender.amqp=org.springframework.amqp.rabbit.log4j.AmqpAppender
log4j.appender.amqp.applicationId=myApplication
log4j.appender.amqp.routingKeyPattern=%X{applicationId}.%c.%p
log4j.appender.amqp.layout=org.apache.log4j.PatternLayout
log4j.appender.amqp.layout.ConversionPattern=%d %p %t [%c] - <%m>%n
log4j.appender.amqp.generateId=true
log4j.appender.amqp.charset=UTF-8
log4j.appender.amqp.durable=false
log4j.appender.amqp.deliveryMode=NON_PERSISTENT
log4j.appender.amqp.declareExchange=true
----

==== Log4j2 Appender

.Example log4j2.xml Snippet
[source, text]
----
<Appenders>
    ...
    <RabbitMQ name="rabbitmq"
        addresses="foo:5672,bar:5672" user="guest" password="guest" virtualHost="/"
        exchange="log4j2" exchangeType="topic" declareExchange="true" durable="true" autoDelete="false"
        applicationId="myAppId" routingKeyPattern="%X{applicationId}.%c.%p"
        contentType="text/plain" contentEncoding="UTF-8" generateId="true" deliveryMode="NON_PERSISTENT"
        charset="UTF-8"
        senderPoolSize="3" maxSenderRetries="5">
    </RabbitMQ>
</Appenders>
----

==== Logback Appender

.Example logback.xml Snippet
[source, text]
----
<appender name="AMQP" class="org.springframework.amqp.rabbit.logback.AmqpAppender">
    <layout>
        <pattern><![CDATA[ %d %p %t [%c] - <%m>%n ]]></pattern>
    </layout>
    <addresses>foo:5672,bar:5672</addresses>
    <abbreviation>36</abbreviation>
    <applicationId>myApplication</applicationId>
    <routingKeyPattern>%property{applicationId}.%c.%p</routingKeyPattern>
    <generateId>true</generateId>
    <charset>UTF-8</charset>
    <durable>false</durable>
    <deliveryMode>NON_PERSISTENT</deliveryMode>
    <declareExchange>true</declareExchange>
</appender>
----

==== Customizing the Messages

Each of the appenders can be subclassed, allowing you to modify the messages before publishing.

.Customizing the Log Messages
[source, java]
----
public class MyEnhancedAppender extends AmqpAppender {

    @Override
    public Message postProcessMessageBeforeSend(Message message, Event event) {
        message.getMessageProperties().setHeader("foo", "bar");
        return message;
    }

}
----
