[[whats-new]]
== What's New

=== Changes in 3.0 Since 2.4

==== Java 17, Spring Framework 6.0

This version requires Spring Framework 6.0 and Java 17

==== Remoting

The remoting feature (using RMI) is no longer supported.

==== AsyncRabbitTemplate

The `AsyncRabbitTemplate2`, which was added in 2.4.7 to aid migration to this release, is deprecated in favor of `AsyncRabbitTemplate`.
The `AsyncRabbitTemplate` now returns `CompletableFuture` s instead of `ListenableFuture` s.
See <<async-template>> for more information.

==== Stream Support Changes

`RabbitStreamOperations2` and `RabbitStreamTemplate2` have been deprecated in favor of `RabbitStreamOperations` and `RabbitStreamTemplate` respectively.
See <<stream-support>> for more information.

==== `@RabbitListener` Changes

Batch listeners can now consume `Collection<?>` as well as `List<?>`.
The batch messaging adapter now ensures that the method is suitable for consuming batches.
When setting the container factory `consumerBatchEnabled` to `true`, the `batchListener` property is also set to `true`.
See <<receiving-batch>> for more infoprmation.

`MessageConverter` s can now return `Optional.empty()` for a null value; this is currently implemented by the `Jackson2JsonMessageConverter`.
See <<Jackson2JsonMessageConverter-from-message>> for more information.
