[[whats-new]]
=== What's New

==== Changes in 1.6 Since 1.5

===== Testing Support

A new testing support library is now provided.
See <<testing>> for more information.

===== Namespace Changes

====== Connection Factory

It is now possible to add a `thread-factory` to a connection factory bean declaration, for example to name the threads
created by the `amqp-client` library.
See <<connections>> for more information.

====== Queue Definitions

It is now possible to provide a naming strategy for anonymous queues; see <<anonymous-queue>> for more information.

===== Listener Container Changes

====== Idle Message Listener Detection

It is now possible to configure listener containers to publish `ApplicationEvent` s when idle.
See <<idle-containers>> for more information.

====== Mismatched Queue Detection

By default, when a listener container starts, if queues with mismatched properties or arguments were detected,
the container would log the exception but continue to listen.
The container now has a property `mismatchedQueuesFatal` which will prevent the container (and context) from
starting if the problem is detected during startup.
It will also stop the container if the problem is detected later, such as after recovering from a connection failure.
See <<containerAttributes>> for more information.

====== Listener Container Logging

Now listener container provides its `beanName` into the internal `SimpleAsyncTaskExecutor` as a `threadNamePrefix`.
It is useful for logs analysis.

===== AutoDeclare and RabbitAdmins

See <<containerAttributes>> (`autoDeclare`) for some changes to the semantics of that option with respect to the use
of `RabbitAdmin` s in the application context.

===== AmqpTemplate: receive with timeout

A number of new `receive()` methods with `timeout` have been introduced for the `AmqpTemplate`
 and its `RabbitTemplate` implementation.
See <<polling-consumer>> for more information.

===== AsyncRabbitTemplate

A new `AsyncRabbitTemplate` has been introduced.
This template provides a number of send and receive methods, where the return value is a `ListenableFuture`, which can
be used later to obtain the result either synchronously, or asynchronously.
See <<async-template>> for more information.

===== RabbitTemplate Changes

1.4.1 introduced the ability to use https://www.rabbitmq.com/direct-reply-to.html[Direct reply-to] when the broker
supports it; it is more efficient than using a temporary queue for each reply.
This version allows you to override this default behavior and use a temporary queue by setting the
`useTemporaryReplyQueues` property to `true`.
See <<direct-reply-to>> for more information.

===== Message Properties

====== CorrelationId

The `correlationId` message property can now be a `String`.
See <<message-properties-converters>> for more information.

====== Long String Headers

Previously, the `DefaultMessagePropertiesConverter` "converted" headers longer than the long string limit (default 1024)
to a `DataInputStream` (actually it just referenced the `LongString`'s `DataInputStream`).
On output, this header was not converted (except to a String, e.g. `java.io.DataInputStream@1d057a39` by calling
`toString()` on the stream).

With this release, long `LongString` s are now left as `LongString` s by default; you can access the contents via
the `getBytes[]`, `toString()`, or `getStream()` methods.
A large incoming `LongString` is now correctly "converted" on output too.

See <<message-properties-converters>> for more information.

===== RabbitAdmin Changes

====== Declaration Failures

Previously, the `ignoreDeclarationFailures` flag only took effect for `IOException` on the channel (such as mis-matched
arguments).
It now takes effect for any exception (such as `TimeoutException`).
In addition, a `DeclarationExceptionEvent` is now published whenever a declaration fails.
The `RabbitAdmin` last declaration event is also available as a property `lastDeclarationExceptionEvent`.
See <<broker-configuration>> for more information.

===== @RabbitListener Changes

When using Java 8 or later, it is now possible to add multiple `@RabbitListener` annotations to `@Bean` classes or
their methods.
When using Java 7 or earlier, you can use the `@RabbitListeners` container annotation to provide the same
functionality.
See <<repeatable-rabbit-listener>> for more information.

===== Delayed Message Exchange

Spring AMQP now has first class support for the RabbitMQ Delayed Message Exchange plugin.
See <<delayed-message-exchange>> for more information.

===== CachingConnectionFactory Cache Statistics

The `CachingConnectionFactory` now provides cache properties at runtime and over JMX.
See <<runtime-cache-properties>> for more information.

==== Earlier Releases

See <<previous-whats-new>> for changes in previous versions.
