[[whats-new]]
== What's New

=== Changes in 2.3 Since 2.2

This section describes the changes between version 2.2 and version 2.3.
See <<change-history>> for changes in previous versions.

==== Connection Factory Changes

Two additional connection factories are now provided.
See <<choosing-factory>> for more information.

==== `@RabbitListener` Changes

You can now specify a reply content type.
See <<reply-content-type>> for more information.

==== Message Converter Changes

The `Jackson2JMessageConverter` s can now deserialize abstract classes (including interfaces) if the `ObjectMapper` is configured with a custom deserializer.
See <<jackson-abstract>> for more information.

==== Testing Changes

A new annotation `@SpringRabbitTest` is provided to automatically configure some infrastructure beans for when you are not using `SpringBootTest`.
See <<spring-rabbit-test>> for more information.

==== RabbitTemplate Changes

The template's `ReturnCallback` has been refactored as `ReturnsCallback` for simpler use in lambda expressions.
See <<template-confirms>> for more information.

==== Listener Container Changes

A new listener container property `consumeDelay` is now available; it is helpful when using the https://github.com/rabbitmq/rabbitmq-sharding[RabbitMQ Sharding Plugin].
See <<containerAttributes>> for more information.
