[[whats-new]]
=== What's New

==== Changes in 2.1 Since 2.0

===== AMQP Client library

Spring AMQP now uses the new 5.2.x version of the `amqp-client` library provided by the RabbitMQ team.
This client has auto recovery configured by default; see <<auto-recovery>>.

NOTE: As of version 4.0, the client enables automatic recovery by default; while compatible with this feature, Spring AMQP has its own recovery mechanisms and the client recovery feature generally isn't needed.
It is recommended to disable `amqp-client` automatic recovery, to avoid getting `AutoRecoverConnectionNotCurrentlyOpenException` s when the broker is available, but the connection has not yet recovered.
Starting with _version 1.7.1_, Spring AMQP disables it unless you explicitly create your own RabbitMQ connection factory and provide it to the `CachingConnectionFactory`.
RabbitMQ `ConnectionFactory` instances created by the `RabbitConnectionFactoryBean` will also have the option disabled by default.


===== Package Changes

Certain classes have moved to different packages; most are internal classes and won't affect user applications.
Two exceptions are `ChannelAwareMessageListener` and `RabbitListenerErrorHandler`; these interfaces are now in `org.springframework.amqp.rabbit.listener.api`.


===== Publisher Confirms Changes

Channels enabled for publisher confirms are not returned to the cache while there are outstanding confirms.
See <<template-confirms>> for more information.


===== Listener Container Factory Improvements

The listener container factories can now be used to create any listener container, not just those for use with `@RabbitListener` s or the `@RabbitListenerEndpointRegistry`.
See <<using-container-factories>> for more information.

`ChannelAwareMessageListener` now inherits from `MessageListener`.

===== Broker Event Listener

A `BrokerEventListener` is introduced to publish selected broker events as `ApplictionEvent` s.
See <<broker-events>> for more information.

===== RabbitAdmin Changes

The `RabbitAdmin` will discover beans of type `Declarables` (which is a container for `Declarable` - `Queue`, `Exchange`, `Binding` objects) and declare the contained objects on the broker.
Users are discouraged from using the old mechanism of declaring `<Collection<Queue>>` etc and should use `Declarables` beans instead.
See <<collection-declaration>> for more information.

===== RabbitTemplate Changes

The `RabbitTemplate` now can be configured with the `noLocalReplyConsumer` option to control a `noLocal` flag for reply consumers in the `sendAndReceive()` operations.
See <<request-reply>> for more information.
