[[whats-new]]
=== What's New

==== Changes in 2.2 Since 2.1

This section describes the changes between version 2.1 and version 2.2.

===== Package Changes

The following classes/interfaces have been moved from `org.springframework.amqp.rabbit.core.support` to `org.springframework.amqp.rabbit.batch`:

* `BatchingStrategy`
* `MessageBatch`
* `SimpleBatchingStrategy`

In addition, `ListenerExecutionFailedException` has been moved from `org.springframework.amqp.rabbit.listener.exception` to `org.springframework.amqp.rabbit.support`.

===== @RabbitListener Changes

You can now configure an `executor` on each listener, overriding the factory configuration, to more easily identify threads associated with the listener.
You can now override the container factory's `acknowledgeMode` property with the annotation's `ackMode` property.
See <<listener-property-overrides,overriding container factory properties>> for more information.

When using <<receiving-batch,batching>>, `@RabbitListener` methods can now receive a complete batch of messages in one call instead of getting them one at at time.

Spring Data Projection interfaces are now supported by the `Jackson2JsonMessageConverter`.
See <<data-projection>> for more information.

===== AMQP Logging Appenders Changes

The Log4J and Logback `AmqpAppender` s now support a `verifyHostname` SSL option.
See <<logging>> for more information.

===== MessageListenerAdapter Changes

The `MessageListenerAdapter` provides now a new `buildListenerArguments(Object, Channel, Message)` method  to build an array of arguments to be passed into target listener and an old one is deprecated.
See <<message-listener-adapter>> for more information.
