[[whats-new]]
=== What's New

==== Changes in 2.2 Since 2.1

This section describes the changes between version 2.1 and version 2.2.

===== Package Changes

The following classes/interfaces have been moved from `org.springframework.amqp.rabbit.core.support` to `org.springframework.amqp.rabbit.batch`:

* `BatchingStrategy`
* `MessageBatch`
* `SimpleBatchingStrategy`

In addition, `ListenerExecutionFailedException` has been moved from `org.springframework.amqp.rabbit.listener.exception` to `org.springframework.amqp.rabbit.support`.

===== @RabbitListener Changes

You can now configure an `executor` on each listener, overriding the factory configuration, to more easily identify threads associated with the listener.
You can now override the container factory's `acknowledgeMode` property with the annotation's `ackMode` property.
See <<listener-property-overrides,overriding container factory properties>> for more information.

When using <<receiving-batch,batching>>, `@RabbitListener` methods can now receive a complete batch of messages in one call instead of getting them one-at-a-time.

When receiving batched messages one-at-a-time, the last message has the `isLastInBatch` message property set to true.

In addition, received batched messages now contain the `amqp_batchSize` header.

Listeners can also consume batches created in the `SimpleMessageListenerContainer`, even if the batch is not created by the producer.
See <<choose-container>> for more information.

Spring Data Projection interfaces are now supported by the `Jackson2JsonMessageConverter`.
See <<data-projection>> for more information.

The `Jackson2JsonMessageConverter` now assumes the content is JSON if there is no `contentType` property, or it is the default (`application/octet-string`).
See <<Jackson2JsonMessageConverter-from-message>> for more information.

Similarly. the `Jackson2XmlMessageConverter` now assumes the content is XML if there is no `contentType` property, or it is the default (`application/octet-string`).
See <<jackson2xml>> for more information.

===== AMQP Logging Appenders Changes

The Log4J and Logback `AmqpAppender` s now support a `verifyHostname` SSL option.

Also these appendes now can be configured to not add MDC entries as headers.
The `addMdcAsHeaders` boolean option has been introduces to configure such a behavior.

The appenders now support the `SaslConfig` property.

See <<logging>> for more information.

===== MessageListenerAdapter Changes

The `MessageListenerAdapter` provides now a new `buildListenerArguments(Object, Channel, Message)` method  to build an array of arguments to be passed into target listener and an old one is deprecated.
See <<message-listener-adapter>> for more information.

===== Exchange/Queue Declaration Changes

The `ExchangeBuilder` and `QueueBuilder` fluent APIs used to create `Exchange` and `Queue` objects for declaration by `RabbitAdmin` now support "well known" arguments.
See <<builder-api>> for more information.

===== Connection Factory Changes

The `CachingConnectionFactory` has a new property `shuffleAddresses`.
When providing a list of broker node addresses, the list will be shuffled before creating a connection so that the order in which the connections are attempted is random.
See <<cluster>> for more information.

===== Other Changes

The `Declarables` object (for declaring multiple queues, exchanges, bindings) now has a filtered getter for each type.
See <<collection-declaration>> for more information.

Outbound headers with values of type `Class<?>` are now mapped using `getName()` instead of `toString()`.
See <<message-properties-converters>> for more information.
