[[whats-new]]
=== What's New

==== Changes in 2.1 Since 2.0

===== AMQP Client library

Spring AMQP now uses the new 5.2.x version of the `amqp-client` library provided by the RabbitMQ team.
This client has auto recovery configured by default; see <<auto-recovery>>.

NOTE: As of version 4.0, the client enables automatic recovery by default; while compatible with this feature, Spring AMQP has its own recovery mechanisms and the client recovery feature generally isn't needed.
It is recommended to disable `amqp-client` automatic recovery, to avoid getting `AutoRecoverConnectionNotCurrentlyOpenException` s when the broker is available, but the connection has not yet recovered.
Starting with _version 1.7.1_, Spring AMQP disables it unless you explicitly create your own RabbitMQ connection factory and provide it to the `CachingConnectionFactory`.
RabbitMQ `ConnectionFactory` instances created by the `RabbitConnectionFactoryBean` will also have the option disabled by default.


===== Package Changes

Certain classes have moved to different packages; most are internal classes and won't affect user applications.
Two exceptions are `ChannelAwareMessageListener` and `RabbitListenerErrorHandler`; these interfaces are now in `org.springframework.amqp.rabbit.listener.api`.

===== Publisher Confirms Changes

Channels enabled for publisher confirms are not returned to the cache while there are outstanding confirms.
See <<template-confirms>> for more information.

===== Listener Container Factory Improvements

The listener container factories can now be used to create any listener container, not just those for use with `@RabbitListener` s or the `@RabbitListenerEndpointRegistry`.
See <<using-container-factories>> for more information.

`ChannelAwareMessageListener` now inherits from `MessageListener`.

===== Broker Event Listener

A `BrokerEventListener` is introduced to publish selected broker events as `ApplicationEvent` s.
See <<broker-events>> for more information.

===== RabbitAdmin Changes

The `RabbitAdmin` will discover beans of type `Declarables` (which is a container for `Declarable` - `Queue`, `Exchange`, `Binding` objects) and declare the contained objects on the broker.
Users are discouraged from using the old mechanism of declaring `<Collection<Queue>>` etc and should use `Declarables` beans instead.
See <<collection-declaration>> for more information.

===== RabbitTemplate Changes

The `RabbitTemplate` now can be configured with the `noLocalReplyConsumer` option to control a `noLocal` flag for reply consumers in the `sendAndReceive()` operations.
See <<request-reply>> for more information.

`CorrelationData` for publisher confirms now has a `ListenableFuture` which can be used to get the acknowledgment instead of using a callback.
When returns and confirms are enabled, the correlation data, if provided, is populated with the returned message.
See <<template-confirms>> for more information.

===== Message Convertion

A new `Jackson2XmlMessageConverter` is introduced to support converting messages from/to XML format.
See <<Jackson2XmlMessageConverter>> for more information.

===== Management REST API

The `RabbitManagementTemplate` is now deprecated in favor of the direct `com.rabbitmq.http.client.Client` (or `com.rabbitmq.http.client.ReactorNettyClient`) usage.
See <<management-rest-api>> for more information.

===== @RabbitListener Changes

The listener container factory can now be configured with a `RetryTemplate` and, optionally, a `RecoveryCallback` used when sending replies.
See <<async-annotation-driven-enable>> for more information.

===== Async @RabbitListener Return

`@RabbitListener` methods can now return `ListenableFuture<?>` or `Mono<?>`.
See <<async-return>> for more information.

===== Connection Factory Bean Changes

The `RabbitConnectionFactoryBean` now calls `enableHostnameVerification()` by default; to revert to the previous behavior, set the `enableHostnameVerification` property to `false`.

===== Listener Container Changes

The default `ConditionalRejectingErrorHandler` will now completely discard messages that cause fatal errors if an `x-death` header is present.
See <<exception-handling>> for more information.
