blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://stackoverflow.com/questions/tagged/spring-amqp
    about: Please ask and answer questions on StackOverflow with the tag spring-amqp, or use the Discussions tab above
