[[amqp10-client]]
= Generic AMQP 1.0 Support

Version 4.1 introduces `spring-amqp-client` module for https://www.amqp.org/resources/specifications[AMQP 1.0] protocol support.

This artifact is based on the https://github.com/apache/qpid-protonj2/blob/main/protonj2-client/README.md[Qpid ProtonJ2 Client Library] and can work with any peers supporting AMQP 1.0 protocol, including RabbitMQ broker.

This dependency has to be added to the project to be able to interact with AMQP 1.0 support:

[tabs]
======
Maven::
+
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>org.springframework.amqp</groupId>
  <artifactId>spring-amqp-client</artifactId>
  <version>{project-version}</version>
</dependency>
----

Gradle::
+
[source,groovy,subs="+attributes"]
----
implementation 'org.springframework.amqp:spring-amqp-client:{project-version}'
----
======

[[amqp10-client-environment]]
== AMQP 1.0 Environment

The `org.apache.qpid:protonj2-client` is so flexible and comes with a convenient API that it can be used in Spring applications even without any dedicated Spring implementations.
For example, the `org.apache.qpid.protonj2.client.Message` class is a builder pattern implementation.
Either way, the `spring-amqp-client` provides high-level Spring pattern implementations for connection lifecycle management and AMQP 1.0 protocol interaction for sending and receiving messages operations.
The AMQP 1.0 environment starts with a `org.apache.qpid.protonj2.client.Client` instance:

[source,java]
----
@Bean
Client protonClient() {
    return Client.create();
}
----

The same `Client` can be used for connecting to different brokers, the connection settings must be provided on a specific connection.
However, this bean is not mandatory, `SingleAmqpConnectionFactory` creates instance internally.
See also <<amqp10-client-connection-factory>> below.

[[amqp10-client-connection-factory]]
== AMQP 1.0 Connection Factory

The `org.springframework.amqp.client.AmqpConnectionFactory` abstraction was introduced to manage `org.apache.qpid.protonj2.client.Connection`.
The `SingleAmqpConnectionFactory` implementation is present to manage one connection and its settings.
The same `Connection` can be shared between many producers and consumers.
The multiplexing is handled by the link abstraction for AMQP 1.0 protocol implementation internally in the AMQP client library.
The `Connection` has recovery capabilities via `ReconnectOptions` provided for the `ConnectionOptions`.

In most cases it is enough to add this bean into the project:

[source,java]
----
@Bean
AmqpConnectionFactory connectionFactory() {
    return new SingleAmqpConnectionFactory();
}
----

See `SingleAmqpConnectionFactory` setters for all connection-specific options, including `host`, `port`, `user`.
The more advance configuration could be done by the `setConnectionOptions(ConnectionOptions)` which is a builder API from ProtonJ library.
The mentioned `SingleAmqpConnectionFactory` instance with all the defaults would connect to the `localhost:5672` with infinite number of reconnections.

NOTE: The `Client` injection can be omitted for the `SingleAmqpConnectionFactory`, and respective instance is created by the factory internally.

[[amqp10-client-api]]
== `AmqpClient`

The `AmqpClient` is a fluent API to perform send and receive operations on messages against AMQP 1.0 protocol.
Requires an `AmqpConnectionFactory` and can be configured with some defaults via `AmqpClient.Builder` API.
The `DefaultAmqpClient` is an internal implementation of the `AmqpClient` contract.
Even if `org.apache.qpid:protonj2-client` library comes with a `org.apache.qpid.protonj2.client.Message` implementation, the `AmqpClient` still exposes an API based on the well-known `org.springframework.amqp.core.Message` with all the supporting classes like `MessageProperties` and `MessageConverter` abstractions.
The conversion to/from `org.apache.qpid.protonj2.client.Message` is done internally in the `AmqpClient` implementation via `ProtonUtils` supporting class.
All send and receive methods return a `CompletableFuture` to get operation results eventually.
An interaction with plain objects require message body conversion and `SimpleMessageConverter` is used by default.
See `AmqpClient.Builder.messageConverter(MessageConverter)` configuration and xref:amqp/message-converters.adoc[] for more information about conversions.

Usually, just one bean like this is enough to perform all the possible send and receive operations:

[source,java]
----
@Bean
AmqpClient amqpClient(AmqpConnectionFactory connectionFactory) {
    return AmqpClient.builder(connectionFactory)
            .defaultToAddress("/queues/some_queue_as_default")
            .messageConverter(new JacksonJsonMessageConverter())
            .build();
}
----

NOTE: In the example above the `/queues/` prefix used for a `defaultToAddress` is an example of the destination address convention in https://www.rabbitmq.com/docs/amqp#addresses[RabbitMQ].

Here are some samples of `AmqpClient` operations:

[source,java]
----
CompletableFuture<Boolean> sendFuture = this.amqpClient.send(Message.create("test_data"));
----

[source,java]
----
CompletableFuture<Boolean> sendFuture =
    this.amqpClient
            .to("/queues/test_queue")
            .message(new org.springframework.amqp.core.Message("test_data2".getBytes()))
            .send();
----

[source,java]
----
CompletableFuture<Boolean> sendFuture =
        this.amqpClient
                .to("/queues/test_queue")
                .body("convert")
                .priority(7)
                .header("test_header", "test_value")
                .messageId("some_id")
                .userId("guest")
                .send();
----

The `AmqpClient` also provides a fluent API to receive messages from addresses on demand.
For that purpose an `AmqpClient.from(String fromAddress)` method should be called returning a `ReceiveSpec` for various receive operations behavior.
All of them produce a `CompletableFuture` with either native ProtonJ message, a Spring AMQP message, or just payload converted from the message's body.
The `receiveAndConvert()` with non-`Object.class` generic argument requires a `messageConverter` in the `AmqpClient` to be as a `SmartMessageConverter`.
For example, when `JacksonJsonMessageConverter` is provided for the `AmqpClient`, the following example would yield a proper data model conversion:

[source,java]
----
record TestData(String data) { }

 this.amqpClient
        .to("/queues/test_queue")
        .body(new TestData("convert"))
        .send();

CompletableFuture<TestData> receiveFuture =
        this.amqpClient.from("/queues/test_queue")
                    .receiveAndConvert();
----

See Javadocs for those methods for more information about the fluent API exposed by the `AmqpClient`.


[[amqp10-client-listener]]
== The AMQP 1.0 Consumer

The event-driven consumer for AMQP 1.0 protocol is implemented as an `AmqpMessageListenerContainer` similar to all other xref:amqp/receiving-messages/async-consumer.adoc[listener container implementations] in the framework.
The `AmqpMessageListenerContainer` requires an `AmqpConnectionFactory` and uses `org.apache.qpid.protonj2.client.Receiver` instances internally to consume messages from the provided `queueNames` (essentially, AMQP 1.o addresses).
The `100` initial credits are used for receiver links by default.
Every settled delivery then replenishes some number of credits for new upcoming messages.
The consumed messages are handled by the provided `MessageListener`, and if the `autoAccept` is set to `false`, an `AmqpAcknowledgment` implementation is populated to respective Spring AMQP message property for manual delivery settlement in the target message listener logic.

The `consumersPerQueue` option (`1` by default) implements a concurrency behavior for each provided address to consume.

The `Duration receiveTimeout` option (`1 second` by default) controls the blocking `Receiver.receive()` operation, which is called in a loop until consumer is stopped.

Each consumer (an internal `AmqpMessageListenerContainer.AmqpConsumer` instance) is scheduled for running via `Executor`.
The `AmqpMessageListenerContainer.taskExecutor` property is set to a `SimpleAsyncTaskExecutor` by default.

The message processing errors can be handled by the `ErrorHandler` configuration.

The `MessageListener` can be proxied in the `AmqpMessageListenerContainer` if some AOP interceptors are provided, e.g. `TransactionInterceptor`.

The `AmqpMessageListenerContainer` also provides `pause()` and `resume()` API to set AMQP link credits to `0` and replenish, respectively.
This functionality leaves a `Receiver` active, but no delivery is coming from the AMQP peer.

The following example demonstrates a simple configuration for `AmqpMessageListenerContainer`:

[source,java]
----
BlockingQueue<Message> receivedMessages = new LinkedBlockingQueue<>();

@Bean
AmqpMessageListenerContainer amqpMessageListenerContainer(AmqpConnectionFactory connectionFactory) {
    var amqpMessageListenerContainer = new AmqpMessageListenerContainer(connectionFactory);
    amqpMessageListenerContainer.setQueueNames("address1", "address2");
    amqpMessageListenerContainer.setConsumersPerQueue(3);
    amqpMessageListenerContainer.setAutoAccept(false);
    amqpMessageListenerContainer.setReceiveTimeout(Duration.ofMillis(100));
    amqpMessageListenerContainer.setupMessageListener(this.receivedMessages::add);
    return amqpMessageListenerContainer;
}
----

=== ProtonJ `Delivery` Consumption

For convenience, a `ProtonDeliveryListener` contract is provided to handle native ProtonJ `Delivery` objects instead of Spring AMQP messages.
It could be useful in scenarios where full control over the `Delivery` instance is required.
For example, adding some reject conditions, handling received data as an `InputStream`, replenishing link credits dynamically, according to some target application logic.
Another scenario of native `Delivery` handling, when both producer and consumer deal with native ProtonJ `Message` contract, including ProtonJ body encoding/decoding internal mechanism (unlike the Spring AMQP message which accepts only `byte[]` bodies).

NOTE: The manual delivery settlement still can be skipped, if the `AmqpMessageListenerContainer` is configured for `autoAccept = true` (default).
And the `AmqpMessageListenerContainer` performs credits replenishment automatically.

The `ProtonDeliveryListener` implementation should be injected into the `AmqpMessageListenerContainer` as a regular `MessageListener`:

[source,java]
----
BlockingQueue<Delivery> receivedDeliveries = new LinkedBlockingQueue<>();

@Bean
AmqpMessageListenerContainer protonDeliveryListenerContainer(AmqpConnectionFactory connectionFactory) {
    var amqpMessageListenerContainer = new AmqpMessageListenerContainer(connectionFactory);
    amqpMessageListenerContainer.setQueueNames(TEST_QUEUE_FOR_NATIVE_PROTON);
    amqpMessageListenerContainer.setAutoAccept(false);
    amqpMessageListenerContainer.setupMessageListener((ProtonDeliveryListener) this.receivedDeliveries::add);
    return amqpMessageListenerContainer;
}
----

[[amqp10-annotation-configuration]]
== The AMQP 1.0 Annotation Configuration

The `spring-amqp-client` provides a convenient way to configure the AMQP 1.0 infrastructure via annotations.
The `@EnableAmqp` annotation can be set on a `@Configuration` class in the target project to trigger that infrastructure registration.
The imported by the `@EnableAmqp` annotation `AmqpDefaultConfiguration` provides infrastructure beans to support `@AmqpListener` (see below):

* The `AmqpListenerEndpointRegistry` - the global component to register AMQP listener containers programmatically.
* The `AmqpListenerAnnotationBeanPostProcessor` (under the `AmqpDefaultConfiguration.AMQP_LISTENER_ANNOTATION_PROCESSOR_BEAN_NAME`) - a `BeanPostProcessor` to parse POJO methods with the `@AmqpListener` and register listener containers via the `AmqpListenerEndpointRegistry`.

=== `@AmqpListener`

For high-level and convenient configuration, the framework provides an `@AmqpListener` annotation to mark POJO methods as listener invokers to be used from the created by the framework `AmqpMessageListenerContainer` instances.
This annotation has many similarities with the `@RabbitListener`, `@KafkaListener`, `@JmsListener`.
It requires AMQP addresses to consume from, and also can be configured with many other listener container properties.
All the `@AmqpListener` attributes can be configured as property-placeholders (`${}`) and/or SpEL expressions (`#{}`).
The request-reply method signature is also supported, where `@SendTo` can be used as a fallback reply address, if `replyTo` is not provided in the request message.
These methods can have asynchronous return types: Project Reactor's `Mono`, `CompletableFuture` or Kotlin `suspend` functions.

* `Mono`-based request-reply example with possible attributes:

[source,java]
----
@Bean
AmqpMessageListenerContainerFactory customContainerFactory(AmqpConnectionFactory connectionFactory) {
	var containerFactory = new MethodAmqpMessageListenerContainerFactory(connectionFactory);
	containerFactory.setAutoStartup(false);
	containerFactory.setAutoAccept(true);
	containerFactory.setConcurrency(5);
	containerFactory.setReceiveTimeout(Duration.ofSeconds(5));
	containerFactory.setGracefulShutdownPeriod(Duration.ofSeconds(36));
	containerFactory.setInitialCredits(55);
	containerFactory.setTaskExecutor(this.taskExecutor);
	containerFactory.setAdviceChain(new DebugInterceptor());
	containerFactory.setListenerErrorHandler(mock());
	containerFactory.setDefaultRequeueRejected(false);
	containerFactory.setHeaderMapper(this.headerMapper);
	containerFactory.setMessageConverter(this.messageConverter);
	return containerFactory;
}

@Bean
TaskExecutor taskExecutor() {
	ThreadPoolTaskExecutor threadPoolTaskExecutor = new ThreadPoolTaskExecutor();
	threadPoolTaskExecutor.setCorePoolSize(10);
	return threadPoolTaskExecutor;
}

@Bean
AmqpHeaderMapper headerMapper() {
	return new SimpleAmqpHeaderMapper();
}

@Bean
DebugInterceptor debugInterceptor() {
	return new DebugInterceptor();
}

@AmqpListener(
        id = "monoListener",
        addresses = TEST_QUEUE2 + "," + TEST_QUEUE3,
        concurrency = "2",
        autoStartup = "#{true}",
        autoAccept = "true",
        containerFactory = "customContainerFactory",
        receiveTimeout = "${receive.timeout:22000}",
        gracefulShutdownPeriod = "pt2m",
        initialCredits = "101",
        defaultRequeueRejected = "true",
        executor = "#{taskExecutor}",
        messageConverter = "jsonMessageConverter",
        headerMapper = "headerMapper",
        adviceChain = "debugInterceptor")
Mono<DataOut> requestReplyWithJsonAndOtherAnnotationAttributes(DataIn dataIn) {
       DataOut dataOut = new DataOut(dataIn.data + "_out");
       return Mono.just(dataOut);
}
----

The `id` attribute is not required, and target listener container bean name will be based on the class name, method name plus `.listenerContainer` suffix.
The `addresses` - can be an array of names, or each item can be a comma-delimited set of names.
This can be useful when a list of AMQP addresses is provided via external configuration properties.
The `containerFactory` (see below), `executor`, `messageConverter` and `headerMapper` attributes are optional and can be configured to bean name or bean reference as a SpEL expression like the `executor` in the sample above.
The `adviceChain` attribute is a list of bean names of `Advice` implementations.

* Kotlin `suspend` function example with an explicit `@SendTo`:

[source,kotlin]
----
@Bean
fun jsonMessageConverter() = JacksonJsonMessageConverter()

@Bean
fun amqpConnectionFactory(protonClient: Client) =
    SingleAmqpConnectionFactory(protonClient)
        .setPort(amqpPort())

@Bean
fun amqpClient(connectionFactory: AmqpConnectionFactory, jsonMessageConverter: MessageConverter) =
    AmqpClient.builder(connectionFactory)
        .messageConverter(jsonMessageConverter)
        .build()

@Bean(AmqpDefaultConfiguration.DEFAULT_AMQP_LISTENER_CONTAINER_FACTORY_BEAN_NAME)
fun containerFactory(connectionFactory: AmqpConnectionFactory, jsonMessageConverter: MessageConverter) =
    MethodAmqpMessageListenerContainerFactory(connectionFactory)
        .also { it.setMessageConverter(jsonMessageConverter) }

@AmqpListener(addresses = ["TEST_QUEUE"])
@SendTo("TEST_REPLY_TO")
suspend fun requestReplyAsyncListener(payload: DataIn) = DataOut(payload.data + "_out")

data class DataIn(val data: String)

data class DataOut(val data: String)
----

The `@AmqpListener` is `@Repeatable`, so several listener containers will be registered for each annotation invoking the same service method.

=== `AmqpMessageListenerContainerFactory`

The `AmqpMessageListenerContainerFactory` abstraction can be used to create an `AmqpMessageListenerContainer` based on the provided `AmqpListenerEndpoint`.
The factory provides default listener container properties if they are not overridden by the `AmqpListenerEndpoint` instance.
The framework provides a `SimpleAmqpListenerEndpoint` implementation based on the `MessageListener` injection, and `MethodAmqpListenerEndpoint` based on the specific POJO method invocation.
Both endpoint implementations require AMQP addresses to consume from.
The `MethodAmqpMessageListenerContainerFactory` extension of the `AmqpMessageListenerContainerFactory` is designed specifically for the `AmqpMessageListenerContainer` instances based on the `MethodAmqpListenerEndpoint` (the `AmqpMessagingListenerAdapter` is used as a message listener internally).
The framework relies on a bean for this factory when `@AmqpListener` annotation is parsed via `AmqpListenerAnnotationBeanPostProcessor`.
If `@AmqpListener(containerFactory)` attribute is not provided on a POJO method, the framework expects a global bean for an `AmqpMessageListenerContainerFactory` with the `AmqpDefaultConfiguration.DEFAULT_AMQP_LISTENER_CONTAINER_FACTORY_BEAN_NAME`.

Unlike with the `@RabbitListener` and `RabbitListenerEndpointRegistry` infrastructure, the `AmqpListenerEndpointRegistry` uses an `AmqpMessageListenerContainerFactory` & `AmqpListenerEndpoint` to created an `AmqpMessageListenerContainer` instance, and registers it as a singleton bean into the application context directly.
The bean name for this `AmqpMessageListenerContainer` instance is a value from the `AmqpListenerEndpoint.getId()` or generated one based on the `MessageListener` class name and `.listenerContainer` suffix, or, in case of `MethodAmqpListenerEndpoint` the service class name plus method name and the mention suffix.

See `AmqpListenerEndpoint`, `AmqpMessageListenerContainerFactory` and `AmqpListenerEndpointRegistry` Javadocs for more information.