[[spring-amqp-reference]]
= Spring AMQP
ifdef::backend-html5[]
:revnumber: ''
endif::[]
:numbered:
:icons: font
:hide-uri-scheme:
Mark Pollack; Mark Fisher; Oleg Zhurakousky; Dave Syer; Gary Russell; Gunnar Hillert; Artem Bilan; Stéphane Nicoll; Arnaud Cogoluègnes; Jay Bryant

[[preface]]
The Spring AMQP project applies core Spring concepts to the development of AMQP-based messaging solutions.
We provide a "`template`" as a high-level abstraction for sending and receiving messages.
We also provide support for message-driven POJOs.
These libraries facilitate management of AMQP resources while promoting the use of dependency injection and declarative configuration.
In all of these cases, you can see similarities to the JMS support in the Spring Framework.
For other project-related information, visit the Spring AMQP project https://projects.spring.io/spring-amqp/[homepage].

(C) 2010 - 2021 by VMware, Inc.

Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.