[[whats-new]]
= What's New
:page-section-summary-toc: 1

[[changes-in-4-2-since-3-2]]
== Changes in 4.0 Since 3.2

[[spring-framework-7-0]]
=== Spring Framework 7.0

This version requires Spring Framework 7.0.

[[x40-null-away]]
=== Null-safety

As many other Spring portfolio projects, Spring AMQP has been migrated to https://jspecify.dev/docs/start-here[JSpecify] annotations to declare the nullness of API.
The https://github.com/uber/NullAway[NullAway] Gradle plugin is used to check the consistency of null-safety declarations.

[[x40-rabbitmq-amqp-client]]
=== The `spring-rabbitmq-client` module

The new `spring-rabbitmq-client` module (with same artifact name) is introduced.
This is an implementation of AMQP 1.0 protocol specific to RabbitMQ since `4.0` and based on the `com.rabbitmq.client:amqp-client` library.

See xref:rabbitmq-amqp-client.adoc[] for more information.

[[x40-junit4-deprecation]]
=== Deprecation of JUnit 4 utilities

The latest JUnit 4 release was `4.13.2` in February 2021 and the next JUnit 6 will be based on Java 17.
There is no need to keep outdated utilities, and the recommendation is to migrate to respective tools for JUnit Jupiter.

[[x40-jackson3-support]]
=== The Jackson 3 Support

The Jackson 2 has been deprecated for removal in the whole Spring portfolio.
Respective new classes have been introduced to support Jackson 3.

See xref:amqp/message-converters.adoc[] for more information.

[[x40-smlc-changes]]
=== MessageListenerContainer Changes

The `SimpleMessageListenerContainer` now awaits at most `shutdownTimeout` for pending replies from the provided `RabbitTemplate` listener on its shutdown.

[[x40-spring-retry-migration]]
=== Migration to Spring Core Retry

The Spring Retry API and usage in the project have been replaced with similar API from `spring-core` module.
The respective `org.springframework.retry:spring-retry` dependency has been removed.
This is a breaking change, but reasonable for the current new major generation of the whole Spring portfolio.
See new convenient classes: `StatelessRetryOperationsInterceptor` and `StatefulRetryOperationsInterceptor`.
The `SendRetryContextAccessor` was removed in favor of the `MessageRecoverer` contract.
The `replyTo` address of the failure could be obtained from the `ReplyFailureException` propagated after retry exhausted into the mentioned `MessageRecoverer`.