[[whats-new]]
= What's New
:page-section-summary-toc: 1

[[changes-in-4-2-since-4-1]]
== Changes in 4.2 Since 4.1

[[x42-tls-hostname-verification]]
=== TLS Hostname Verification

The `RabbitConnectionFactoryBean#setEnableHostnameVerification(boolean)` is deprecated now.
Since `amqp-client` 5.33, hostname verification is enabled automatically whenever TLS is configured through `useSslProtocol`.
See xref:amqp/connections.adoc[] for more information.

For the same reason, the `verifyHostname` property on the Logback and Log4j 2 `AmqpAppender` s is also deprecated now.
See xref:logging.adoc[] for more information.

[[x42-listener-batch-overrides]]
=== `@RabbitListener` Batch Overrides

The `@RabbitListener` annotation has new `batchSize()` and `batchReceiveTimeout()` attributes to override the respective container factory properties for a single listener.
See xref:amqp/receiving-messages/batch.adoc[] for more information.

[[x42-routing-amqp-connection-factory]]
=== Routing AMQP Connection Factory

The `spring-rabbitmq-client` module now provides an `AbstractRoutingAmqpConnectionFactory` (and a `SimpleRoutingAmqpConnectionFactory` implementation) to route to one of several `AmqpConnectionFactory` instances based on a runtime `lookupKey`.
See xref:rabbitmq-amqp-client.adoc#amqp-client-routing-connection-factory[Routing Connection Factory] for more information.
