/*
 * Copyright 2018-present the original author or authors.
 */

package org.springframework.amqp.rabbit.core;

import java.util.Map;

import org.jspecify.annotations.Nullable;

import org.springframework.amqp.core.MessageProperties;
import org.springframework.amqp.event.AmqpEvent;
import org.springframework.util.Assert;

/**
 * Represents a broker event generated by the
 * <a href="https://www.rabbitmq.com/event-exchange.html">Event Exchange Plugin</a>.
 *
 * @author Gary Russell
 * @author Artem Bilan
 *
 * @since 2.1
 *
 */
@SuppressWarnings("serial")
public class BrokerEvent extends AmqpEvent {

	private final MessageProperties properties;

	/**
	 * Create an instance with the provided source and properties.
	 * @param source the source.
	 * @param properties the properties.
	 */
	public BrokerEvent(Object source, MessageProperties properties) {
		super(source);
		Assert.notNull(properties, "MessageProperties cannot be null");
		this.properties = properties;
	}

	/**
	 * The event type ({@link MessageProperties#getReceivedRoutingKey()}).
	 * @return the type.
	 */
	public @Nullable String getEventType() {
		return this.properties.getReceivedRoutingKey();
	}

	/**
	 * Properties of the event {@link MessageProperties#getHeaders()}.
	 * @return the properties.
	 */
	public Map<String, @Nullable Object> getEventProperties() {
		return this.properties.getHeaders();
	}

	/**
	 * The complete {@link MessageProperties} from the event representing the event.
	 * (The body is always blank).
	 * @return the message properties.
	 */
	public MessageProperties getMessageProperties() {
		return this.properties;
	}

	@Override
	public String toString() {
		return "BrokerEvent [eventType=" + this.getEventType() + ", properties=" + this.getEventProperties() + "]";
	}

}
